### PR TITLE
Battery fixes

### PR DESCRIPTION
**Pull request by spinal84**
Fix bq27xxx_battery and remove rx51-battery from DTS. See commits description for details.

### CODE REVIEW

**Comment by MerlijnWajer** [comment]
What does rx51-battery provide that is not available elsewhere? What is the added value in the first place?

**Comment by spinal84** [comment]
> What does rx51-battery provide that is not available elsewhere? What is the added value in the first place?

The only "value" it had was a hardcoded value for maximum design voltage of 4.2V when the battery is full.
Is there something else I'm missing?

**Comment by MerlijnWajer** [comment]
Perhaps several of these commits can also go to `linux-omap`, would you like me to submit them? The 4.21 merge window is now open IIRC.

**Comment by spinal84** [comment]
That would be nice. Thanks!

**Comment by MerlijnWajer** [comment]
@freemangordon - changes look OK to me, what do you think?

**Comment by spinal84** [comment]
Should fix https://github.com/maemo-leste/bugtracker/issues/85

**Comment by MerlijnWajer** [comment]
Regarding disabling nowayout, I've suggested this a couple of times in the past, but I agree it might not be the right solution. What if the device hangs after dsme stops?

**Comment by spinal84** [comment]
> Regarding disabling nowayout, I've suggested this a couple of times in the past, but I agree it might not be the right solution. What if the device hangs after dsme stops?

For the current state of things this approach is better, than what we have.
No one has implemented a proper solution. And the users/developers suffer because of this.

We have the bug with dsme not fixed for several months already, and who knows how long it will take?

> What if the device hangs after dsme stops?

Just remove the battery and place it again. If you care, how to know the device is hanging: just press power off button for a short period of time. If the white LED blinks, then it's ok - the device is powered off.

Of course we can enable nowayout later, when someone implements proper dsme poweroff with watchdog nowayout enabled. But now it just breaks the things. At least for openrc.

**Comment by MerlijnWajer** [comment]
I am inclined to agree. @freemangordon - can you also accept this as temporary stopgap, since it's only for n900 kernel, and we can remove battery as spinal said?

**Pull request merged**
